cd C:\pleiades\workspace\kabuAuto\src\main\webapp\WEB-INF

java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 3250 ADワークス
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 4798 (株)エル・シー・エーホールディングス
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 7638 (株)シーマ
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 8918 (株)ランド
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 9318 アジア・アライアンス・ホールディングス(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 9898 (株)サハダイヤモンド
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 1491 中外鉱業(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 1844 (株)大盛工業
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 3250 (株)エー・ディー・ワークス
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 8893 (株)新日本建物
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 1757 クレアホールディングス(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 8894 (株)原弘産
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 3318 (株)メガネスーパー
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 3350 (株)レッド・プラネット・ジャパン
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 5721 (株)エス・サイエンス
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 3587 グローバルアジアホールディングス(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 7708 石山Ｇａｔｅｗａｙ　Ｈｏｌｄｉｎｇｓ(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 9423 (株)ＦＲＳ
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 5955 (株)ヤマシナ
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 8836 (株)ＲＩＳＥ
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 2759 (株)アイフラッグ
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 6819 ソーシャル・エコロジー・プロジェクト(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 7610 (株)テイツー
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 8685 ＡＩＧ
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 8710 シティグループ
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 5856 (株)東理ホールディングス
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 8704 トレイダーズホールディングス(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 5103 昭和ホールディングス(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 3779 ジェイ・エスコム　ホールディングス(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 8256 (株)プロルート丸光
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 7571 (株)ヤマノホールディングス
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 2666 (株)オートウェーブ
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 6835 アライドテレシスホールディングス(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 3323 レカム(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 6494 (株)ＮＦＫホールディングス
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 1783 (株)Ａ．Ｃホールディングス
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 8107 (株)キムラタン
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 3719 (株)ジェクシード
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 3390 ユニバーサルソリューションシステムズ(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 7527 (株)システムソフト
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 2060 フィード・ワンホールディングス(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 3266 (株)ファンドクリエーショングループ
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 3606 (株)レナウン
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 3315 日本コークス工業(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 6625 ＪＡＬＣＯホールディングス(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 2134 燦キャピタルマネージメント(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 1514 住石ホールディングス(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 3331 (株)雑貨屋ブルドッグ
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 8927 (株)明豊エンタープライズ
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 3011 (株)バナーズ
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 7624 (株)ＮａＩＴＯ
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 9973 (株)小僧寿し
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 2353 日本駐車場開発(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 6495 (株)宮入バルブ製作所
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 1821 三井住友建設(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 9479 (株)インプレスホールディングス
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 8073 (株)ＭＡＧねっとホールディングス
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 2694 (株)ジー・テイスト
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 6400 不二精機(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 6731 (株)ピクセラ
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 8263 (株)ダイエー
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 7834 マルマン(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 8175 (株)ベスト電器
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 3845 (株)アイフリークホールディングス
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 7897 ホクシン(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 8589 (株)アプラスフィナンシャル
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 3121 マーチャント・バンカーズ(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 7873 (株)アーク
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 2673 夢みつけ隊(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 6628 オンキヨー(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 3777 (株)ジオネクスト
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 1906 (株)細田工務店
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 6993 アジアグロースキャピタル(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 7859 (株)アルメディオ
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 2170 (株)リンクアンドモチベーション
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 3264 (株)アスコット
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 5216 (株)倉元製作所
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 3776 (株)ブロードバンドタワー
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 2776 (株)クリムゾン
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 5940 不二サッシ(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 7836 アビックス(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 6888 アクモス(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 2768 双日(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 4358 (株)ティー・ワイ・オー
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 2388 (株)ウェッジホールディングス
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 9930 北沢産業(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 5703 日本軽金属ホールディングス(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 8462 フューチャーベンチャーキャピタル(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 1400 ルーデン・ホールディングス(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 2479 (株)ジェイテック
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 7625 (株)グローバルダイニング
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 9478 ＳＥホールディングス・アンド・インキュベーションズ(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 4779 ソフトブレーン(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 9980 マルコ(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 2435 (株)シダー
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 2901 石垣食品(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 6881 (株)キョウデン
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 6334 明治機械(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 7415 (株)新星堂
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 7452 (株)マツヤ
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 5448 東京鋼鐵(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 6775 (株)ＴＢグループ
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 7461 (株)キムラ
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 9748 (株)ＮＪＫ
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 3441 (株)山王
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 7819 ＳＨＯ?ＢＩ(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 5289 ゼニス羽田ホールディングス(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 7022 サノヤスホールディングス(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 5386 (株)鶴弥
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 8944 (株)ランドビジネス
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 3225 東京建物不動産販売(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 3895 ハビックス(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 5367 (株)ニッカトー
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 8127 ヤマト　インターナショナル(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 2162 日本マニュファクチャリングサービス(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 6593 ローヤル電機(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 7544 (株)スリーエフ
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 9758 ジャパンシステム(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 1332 日本水産(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 6740 (株)ジャパンディスプレイ
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 9760 (株)進学会
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 2136 (株)ヒップ
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 6384 (株)昭和真空
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 6719 富士通コンポーネント(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 2538 ジャパン・フード＆リカー・アライアンス(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 7868 (株)廣済堂
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 4743 (株)アイティフォー
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 4838 (株)スペースシャワーネットワーク
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 6259 大崎エンジニアリング(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 6786 (株)リアルビジョン
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 7593 ＶＴホールディングス(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 7928 旭化学工業(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 8118 (株)キング
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 7879 (株)ノダ
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 8622 水戸証券(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 6266 タツモ(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 6791 日本コロムビア(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 9476 (株)中央経済社
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 7922 三光産業(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 8018 三共生興(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 7923 トーイン(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 8718 ＪＰＮホールディングス(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 7238 曙ブレーキ工業(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 4237 フジプレアム(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 7895 中央化学(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 1914 日本基礎技術(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 1879 新日本建設(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 2773 (株)ミューチュアル
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 9501 東京電力(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 2714 プラマテルズ(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 7502 (株)プラザクリエイト
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 8746 第一商品(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 8885 (株)ラ・アトレ
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 7647 (株)音通
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 7883 サンメッセ(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 2164 (株)地域新聞社
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 5997 協立エアテック(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 4689 ヤフー(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 2789 (株)カルラ
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 6727 (株)ワコム
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 3409 北日本紡績(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 4080 (株)田中化学研究所
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 4220 リケンテクノス(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 4335 (株)アイ・ピー・エス
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 1921 (株)巴コーポレーション
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 3366 (株)一六堂
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 4410 ハリマ化成グループ(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 2307 (株)クロスキャット
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 6210 東洋機械金属(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 8103 明和産業(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 8515 アイフル(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 5020 ＪＸホールディングス(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 3765 ガンホー・オンライン・エンターテイメント(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 6853 (株)共和電業
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 9885 (株)シャルレ
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 2399 (株)綜合臨床ホールディングス
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 3271 (株)ＴＨＥグローバル社
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 8070 東京産業(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 3370 (株)フジタコーポレーション
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 2766 日本風力開発(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 3010 価値開発(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 4312 サイバネットシステム(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 8889 (株)アパマンショップホールディングス
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 6476 (株)富士テクニカ宮津
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 1890 東洋建設(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 8524 (株)北洋銀行
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 2667 (株)イメージ　ワン
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 4234 (株)サンエー化研
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 4625 アトミクス(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 9890 (株)マキヤ
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 8732 (株)マネーパートナーズグループ
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 6158 (株)和井田製作所
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 9969 (株)ショクブン
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 6633 (株)Ｃ＆Ｇシステムズ
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 9704 (株)アゴーラ・ホスピタリティー・グループ
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 8120 (株)大木
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 1873 東日本ハウス(株)
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 7455 (株)三城ホールディングス
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 3811 (株)ビットアイル
java -cp ./lib/*;./classes; kabuAuto.batch.MainKabu1 7167 (株)足利ホールディングス
